spring:
  application:
    name: wishlist
  data:
    mongo:
      uri: mongodb://user:pass@localhost:27017/?tls=true&authSource=admin
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    allow-bean-definition-overriding: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
